# Generated by Django 6.1.1 on 2026-09-23 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_code', models.CharField(max_length=50, unique=True)),
                ('student_name', models.CharField(max_length=100)),
                ('course_title', models.CharField(max_length=200)),
                ('issue_date', models.CharField(max_length=50)),
                ('grade', models.CharField(default='A+', max_length=20)),
                ('instructor_name', models.CharField(default='Dr. Aris Vance', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('level', models.CharField(default='Beginner to Advanced', max_length=50)),
                ('rating', models.FloatField(default=4.8)),
                ('reviews_count', models.IntegerField(default=120)),
                ('image_url', models.TextField(blank=True, default='')),
                ('syllabus_json', models.TextField(default='[]')),
                ('trainer_name', models.CharField(max_length=100)),
                ('trainer_role', models.CharField(max_length=150)),
                ('mode', models.CharField(default='Online & Offline', max_length=50)),
                ('tags', models.CharField(default='Top Rated, Job Guarantee', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='DemoBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('course_interest', models.CharField(max_length=200)),
                ('slot_date', models.CharField(max_length=50)),
                ('slot_time', models.CharField(max_length=50)),
                ('status', models.CharField(default='Confirmed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_email', models.CharField(max_length=120)),
                ('student_phone', models.CharField(max_length=30)),
                ('course_id', models.IntegerField()),
                ('course_title', models.CharField(max_length=200)),
                ('batch_code', models.CharField(max_length=50)),
                ('total_fee', models.FloatField()),
                ('payment_status', models.CharField(default='Completed', max_length=50)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('course_name', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(default='New', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(default='student', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=50, unique=True)),
                ('start_date', models.CharField(max_length=50)),
                ('timings', models.CharField(max_length=100)),
                ('mode', models.CharField(default='Live Online', max_length=50)),
                ('seats_total', models.IntegerField(default=30)),
                ('seats_left', models.IntegerField(default=5)),
                ('instructor', models.CharField(max_length=100)),
                ('status', models.CharField(default='Filling Fast', max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='api.course')),
            ],
        ),
    ]
