-- =========================================================
-- TechAcademy IT Training Institute - Supabase PostgreSQL Schema
-- Run this script in your Supabase SQL Editor (https://supabase.com)
-- =========================================================

-- 1. USERS TABLE (Student & Admin Accounts)
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(120) UNIQUE NOT NULL,
    phone VARCHAR(30) DEFAULT '',
    password VARCHAR(100) NOT NULL,
    role VARCHAR(20) DEFAULT 'student',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. COURSES TABLE
CREATE TABLE IF NOT EXISTS public.courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    category VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    duration VARCHAR(50) NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    discount_price NUMERIC(10, 2) NOT NULL,
    level VARCHAR(50) DEFAULT 'Beginner to Advanced',
    rating NUMERIC(3, 2) DEFAULT 4.80,
    reviews_count INT DEFAULT 120,
    image_url TEXT DEFAULT '',
    syllabus_json JSONB DEFAULT '[]'::jsonb,
    trainer_name VARCHAR(100) NOT NULL,
    trainer_role VARCHAR(150) NOT NULL,
    mode VARCHAR(50) DEFAULT 'Online & Offline',
    tags TEXT DEFAULT 'Top Rated, Job Guarantee'
);

-- 3. BATCHES TABLE
CREATE TABLE IF NOT EXISTS public.batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT REFERENCES public.courses(id) ON DELETE CASCADE,
    batch_code VARCHAR(50) UNIQUE NOT NULL,
    start_date VARCHAR(50) NOT NULL,
    timings VARCHAR(100) NOT NULL,
    mode VARCHAR(50) DEFAULT 'Live Online',
    seats_total INT DEFAULT 30,
    seats_left INT DEFAULT 5,
    instructor VARCHAR(100) NOT NULL,
    status VARCHAR(50) DEFAULT 'Filling Fast'
);

-- 4. ENROLLMENTS TABLE
CREATE TABLE IF NOT EXISTS public.enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name VARCHAR(100) NOT NULL,
    student_email VARCHAR(120) NOT NULL,
    student_phone VARCHAR(30) NOT NULL,
    course_id BIGINT NOT NULL,
    course_title VARCHAR(200) NOT NULL,
    batch_code VARCHAR(50) NOT NULL,
    total_fee NUMERIC(10, 2) NOT NULL,
    payment_status VARCHAR(50) DEFAULT 'Completed',
    enrolled_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. DEMO BOOKINGS TABLE
CREATE TABLE IF NOT EXISTS public.demo_bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(120) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    course_interest VARCHAR(200) NOT NULL,
    slot_date VARCHAR(50) NOT NULL,
    slot_time VARCHAR(50) NOT NULL,
    status VARCHAR(50) DEFAULT 'Confirmed',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. INQUIRIES TABLE
CREATE TABLE IF NOT EXISTS public.inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(120) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    course_name VARCHAR(200) DEFAULT '',
    message TEXT NOT NULL,
    status VARCHAR(50) DEFAULT 'New',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. CERTIFICATES TABLE
CREATE TABLE IF NOT EXISTS public.certificates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    certificate_code VARCHAR(50) UNIQUE NOT NULL,
    student_name VARCHAR(100) NOT NULL,
    course_title VARCHAR(200) NOT NULL,
    issue_date VARCHAR(50) NOT NULL,
    grade VARCHAR(20) DEFAULT 'Distinction (A+)',
    instructor_name VARCHAR(100) DEFAULT 'Dr. Aris Vance'
);

-- =========================================================
-- ENABLE ROW LEVEL SECURITY (RLS) POLICIES
-- =========================================================
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.demo_bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.certificates ENABLE ROW LEVEL SECURITY;

-- Allow Public Anonymous Read & Write
CREATE POLICY "Public Read Users" ON public.users FOR SELECT USING (true);
CREATE POLICY "Public Insert Users" ON public.users FOR INSERT WITH CHECK (true);

CREATE POLICY "Public Read Courses" ON public.courses FOR SELECT USING (true);
CREATE POLICY "Public Insert Courses" ON public.courses FOR INSERT WITH CHECK (true);

CREATE POLICY "Public Read Batches" ON public.batches FOR SELECT USING (true);
CREATE POLICY "Public Insert Batches" ON public.batches FOR INSERT WITH CHECK (true);

CREATE POLICY "Public Read Enrollments" ON public.enrollments FOR SELECT USING (true);
CREATE POLICY "Public Insert Enrollments" ON public.enrollments FOR INSERT WITH CHECK (true);

CREATE POLICY "Public Read Demo Bookings" ON public.demo_bookings FOR SELECT USING (true);
CREATE POLICY "Public Insert Demo Bookings" ON public.demo_bookings FOR INSERT WITH CHECK (true);

CREATE POLICY "Public Read Inquiries" ON public.inquiries FOR SELECT USING (true);
CREATE POLICY "Public Insert Inquiries" ON public.inquiries FOR INSERT WITH CHECK (true);

CREATE POLICY "Public Read Certificates" ON public.certificates FOR SELECT USING (true);
CREATE POLICY "Public Insert Certificates" ON public.certificates FOR INSERT WITH CHECK (true);

-- =========================================================
-- SEED INITIAL DATA IN SUPABASE
-- =========================================================
INSERT INTO public.users (name, email, phone, password, role)
VALUES
  ('Daniel Kim', 'student@example.com', '+1 555-492-1049', 'student123', 'student'),
  ('Executive Director', 'admin@techacademy.pro', '+1 800-555-8324', 'admin123', 'admin')
ON CONFLICT (email) DO NOTHING;

INSERT INTO public.courses (title, category, description, duration, price, discount_price, level, rating, reviews_count, image_url, syllabus_json, trainer_name, trainer_role, mode, tags)
VALUES
  ('Full Stack Python Web Development', 'Software Engineering', 'Master modern web app development using Python 3, Django, Flask, FastAPI, React 18, and PostgreSQL/SQLite with real-world enterprise projects.', '16 Weeks (4 Months)', 899.00, 499.00, 'Beginner to Pro', 4.90, 340, 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=60', '[{"module": "Module 1: Python Fundamentals", "topics": ["Variables", "OOP", "SQLite"]}, {"module": "Module 2: Backend & Supabase", "topics": ["REST APIs", "PostgreSQL", "Auth"]}]'::jsonb, 'Alexander Hayes', 'Ex-Google Staff Engineer', 'Live Online & Offline Hybrid', '100% Placement Support, Live Capstone'),
  ('Artificial Intelligence & Machine Learning Specialist', 'Data & AI', 'Deep dive into Supervised/Unsupervised ML, Deep Learning with PyTorch, NLP, Computer Vision, and Generative AI LLMs.', '20 Weeks (5 Months)', 1199.00, 699.00, 'Intermediate', 4.95, 285, 'https://images.unsplash.com/photo-1677442136019-21780efad99a?w=800&auto=format&fit=crop&q=60', '[{"module": "Module 1: Math & Python", "topics": ["NumPy", "Pandas", "Linear Algebra"]}]'::jsonb, 'Dr. Sophia Lin', 'Principal AI Researcher', 'Live Interactive Classes', 'Hot Skill 2026, GPU Lab Access'),
  ('AWS Cloud Architect & DevOps Engineering', 'Cloud & Infrastructure', 'Learn Kubernetes, Docker, Terraform, CI/CD pipelines, Ansible, AWS Core Services for cloud infrastructure.', '14 Weeks (3.5 Months)', 999.00, 549.00, 'Intermediate', 4.88, 412, 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=60', '[{"module": "Module 1: Cloud & AWS Core", "topics": ["VPC", "EC2", "S3", "Lambda"]}]'::jsonb, 'Marcus Vance', 'Lead DevOps Architect', 'Weekend & Weekday Batches', 'AWS Exam Voucher, Real Production Labs')
ON CONFLICT DO NOTHING;

INSERT INTO public.certificates (certificate_code, student_name, course_title, issue_date, grade, instructor_name)
VALUES
  ('CERT-2026-PY892', 'Daniel Kim', 'Full Stack Python Web Development', '2026-08-28', 'Distinction (A+)', 'Alexander Hayes')
ON CONFLICT (certificate_code) DO NOTHING;

INSERT INTO public.enrollments (student_name, student_email, student_phone, course_id, course_title, batch_code, total_fee, payment_status)
VALUES
  ('Daniel Kim', 'student@example.com', '+1 555-492-1049', 1, 'Full Stack Python Web Development', 'PY-FEB26-A', 499.00, 'Completed');
